version: '3.7'

services:
  api:
    image: flyzone_api
    build: 
      context: ./
      dockerfile: ./Dockerfile.api
    env_file:
      - .env     
    environment:  
        RANKS_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}  
        EVENTS_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
        USERS_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
        COGNITO_REGION: ${COGNITO_REGION}
        COGNITO_POOL_ID: ${COGNITO_POOL_ID}
        COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "${API_LOCAL_PORT}:80"
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_USER}@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres